name: ci

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".github/**"
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  FETCH_DEPTH: 0
  USE_CROSS: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
      - name: check
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ env.USE_CROSS }}
          command: check
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ env.USE_CROSS }}
          command: test

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ env.USE_CROSS }}
          command: fmt
          args: --all -- --check

  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
          components: clippy
      - name: clippy-check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          use-cross: ${{ env.USE_CROSS }}
          args: --all-features
